### ISSUE TITLE
Multiple Controllers

### ISSUE THREAD

**Issue by crazyuav** [lxi-tools/libhislip#2]
Generally,an LXI instrument's host should support at least two network instrument servers simultaneously,but I only implement a sever which can be accessed by one controller.
I have no idea about Multiple Controllers!
Can you give me a Sever example Which can be safety accessed by multiple controllers simultaneously.

  Thanks!

**Comment by lundmar** [comment]
Sorry, I have no such example.

FYI - libhislip is work in progress. It is by no means functional yet.
